import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the user slice
const initialState = {
  currentUser: null, // Stores the currently signed-in user
  error: null, // Stores any error messages related to sign-in
  loading: false, // Indicates whether a sign-in process is ongoing
};

// Create a slice for user authentication
const userSlice = createSlice({
  name: "user", // Name of the slice
  initialState, // Initial state of the slice
  reducers: {
    // Action to indicate the start of the sign-in process
    signInStart: (state) => {
      state.loading = true; // Set loading to true
    },
    // Action to handle successful sign-in
    signInSuccess: (state, action) => {
      state.currentUser = action.payload; // Set the current user to the payload
      state.loading = false; // Set loading to false
      state.error = null; // Clear any previous errors
    },
    // Action to handle sign-in failure
    signInFailure: (state, action) => {
      state.error = action.payload; // Set the error to the payload
      state.loading = false; // Set loading to false
    },
  },
});

// Export the actions generated by createSlice
export const { signInStart, signInSuccess, signInFailure } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
